"""Comment table new field is rating

Revision ID: 0e13724cce5a
Revises: ff61724060e6
Create Date: 2026-03-08 20:56:45.702007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e13724cce5a"
down_revision: Union[str, Sequence[str], None] = "ff61724060e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("rating", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments", "rating")
    # ### end Alembic commands ###
