"""shop is_active field add

Revision ID: 1904f816ced4
Revises: a16644cb3364
Create Date: 2026-03-06 11:23:29.091651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1904f816ced4"
down_revision: Union[str, Sequence[str], None] = "a16644cb3364"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shops", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops", "is_active")
    # ### end Alembic commands ###
