"""add_is_verified_avatar_id

Revision ID: 3e8c07d68180
Revises: e86b52d9c71b
Create Date: 2026-04-15 09:58:53.298051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8c07d68180'
down_revision: Union[str, Sequence[str], None] = 'e86b52d9c71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('avatar_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'images', ['avatar_id'], ['id'], ondelete='SET NULL')
    # Note: is_deleted is kept for soft-delete logic; Alembic incorrectly detected it as removed.
    # op.drop_column('users', 'is_deleted')  # <- do NOT drop
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_id')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
