"""new models

Revision ID: 53b817550ac8
Revises: a80249f189ad
Create Date: 2026-02-24 20:13:43.702573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "53b817550ac8"
down_revision: Union[str, Sequence[str], None] = "a80249f189ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_carts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("total_price", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item_carts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_cart_id", sa.BigInteger(), nullable=False),
        sa.Column("item_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_cart_id"], ["user_carts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item_discounts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("item_id", sa.BigInteger(), nullable=False),
        sa.Column("discount_id", sa.BigInteger(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["discount_id"],
            ["discounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("comments", sa.Column("text", sa.Text(), nullable=False))
    op.drop_column("comments", "disadvantages")
    op.drop_column("comments", "advantages")
    op.drop_column("comments", "description")
    op.add_column(
        "delivery_points", sa.Column("region_id", sa.BigInteger(), nullable=False)
    )
    op.create_foreign_key(None, "delivery_points", "regions", ["region_id"], ["id"])
    op.drop_column("delivery_points", "country")
    op.drop_column("delivery_points", "city")
    op.drop_column("delivery_points", "name")
    op.drop_column("delivery_points", "region")
    op.drop_constraint(op.f("discounts_shop_id_fkey"), "discounts", type_="foreignkey")
    op.drop_column("discounts", "end_date")
    op.drop_column("discounts", "start_date")
    op.drop_column("discounts", "shop_id")
    op.drop_constraint(op.f("items_discount_id_fkey"), "items", type_="foreignkey")
    op.drop_column("items", "discount_id")
    op.drop_column("items", "old_price")
    op.add_column("orders", sa.Column("user_card_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(
        None, "orders", "user_carts", ["user_card_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("orders", "bucket_id")
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column(
        "users", sa.Column("deleted_email", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_email")
    op.drop_column("users", "is_deleted")
    op.add_column(
        "orders",
        sa.Column("bucket_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "user_card_id")
    op.add_column(
        "items", sa.Column("old_price", sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "items",
        sa.Column("discount_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("items_discount_id_fkey"),
        "items",
        "discounts",
        ["discount_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "discounts",
        sa.Column("shop_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "discounts",
        sa.Column(
            "start_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "discounts",
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("discounts_shop_id_fkey"), "discounts", "shops", ["shop_id"], ["id"]
    )
    op.add_column(
        "delivery_points",
        sa.Column(
            "region", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "delivery_points",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "delivery_points",
        sa.Column("city", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.add_column(
        "delivery_points",
        sa.Column(
            "country", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "delivery_points", type_="foreignkey")
    op.drop_column("delivery_points", "region_id")
    op.add_column(
        "comments",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "comments",
        sa.Column("advantages", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "comments",
        sa.Column("disadvantages", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("comments", "text")
    op.drop_table("item_discounts")
    op.drop_table("item_carts")
    op.drop_table("user_carts")
    op.drop_table("regions")
    # ### end Alembic commands ###
