"""empty message

Revision ID: a16644cb3364
Revises: da08baf3973d
Create Date: 2026-03-01 13:31:46.957734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a16644cb3364"
down_revision: Union[str, Sequence[str], None] = "da08baf3973d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blanc_lists",
        sa.Column("token", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_blanc_lists")
    # ### end Alembic commands ###
