"""LIke table created-at

Revision ID: ff61724060e6
Revises: 1904f816ced4
Create Date: 2026-03-08 17:52:14.051155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff61724060e6"
down_revision: Union[str, Sequence[str], None] = "1904f816ced4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "likes", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("likes", "created_at")
    # ### end Alembic commands ###
